### ISSUE TITLE
Error with Pick primary samples

### ISSUE THREAD

**Issue by cedunia** [CellCognition/cecog#202]
I've got this error when i click on pick primary samples. 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cecog/threads/corethread.py", line 85, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/cecog/threads/picker.py", line 71, in _run
    learner=learner)
  File "/usr/local/lib/python2.7/dist-packages/cecog/analyzer/core.py", line 269, in __init__
    raise RuntimeError(msg)
RuntimeError: Something is wrong with your annotation files in the classifier folder. Please make sure that the XML have consistent plate names.

I use example battery_package/Classifier/H2B.

Thanks

**Comment by rhoef** [comment]
Hi,

did you use the classifier from the battery package?

**Comment by cedunia** [comment]
Yes i did. 
I used the classifier from battery_package. URL for classifier folder is home/.CellCognition1.6.0/battery_package/Classifier/H2B

**Comment by rhoef** [comment]
Hi, 
sorry for the late reply. You need to train a classifer form you own image data. 

I assume you have scanned your image/input directory. Next open the Annotation Browser
Section Classification -> press button "Open Annotation Browser"
or Menu Browser -> "Open Browser"

The Browser has 3 Buttons on the top (Navigation, Display and Annotation).

In Display you can turn on (checkbox Detect objects) segmentation. If on, anytime you change the image in the Navigation, the contours of the cells are displayed to. 

For classifier training you need to setup a class definition (add button in section Annotation). 
Add a few classes to play arround with. Click on one class in the list. (whole line is highlighted in the class color). Now click on a cell in the image. Its color should change to the class color. 

Save the classifier. The directory path is important. To use this particular classifier use the same path in Section Classification in the main GUI.

**Comment by ThomasWalter** [comment]
Hello. 

As far as I understand, Cedunia wants already to get the battery package working before training his own classifier. The error indicated refers to some inconsistency regarding the naming of the xml-files. I could also reproduce the error ... I will check what happens. In my opinion this is due to the plate names. Normally, the plate names are in the xml-filenames, and this seems not to be the case for the current battery package. 

Thomas.

**Comment by ThomasWalter** [comment]
Ok, there are actually a number of reasons why the picking does not work in the battery package. First, the data in the battery_package is only a subset of the data that is in the training set. So, there are annotations for which no data is in the battery package. The reason for this is that if we put all the data to the battery package, it will be a bit heavy for downloading. But you can download the data set from http://www.cellcognition.org/downloads/data . 

What you need for this: 
Raw data
--> Images (ZIP, reduced set for classifier retraining, 3 positions, 899.6 MB)

In addition however, there was a change in the naming of the xml-files; I still need to check what happens. 

However, what you can do is to omit the picking step and to train and apply the classification. 

Best, 

Thomas.

**Comment by JJMK** [comment]
Hi,

I am having the same issue and am not quite sure how to resolve it. Is there a manual for the cellcognition program that could help me retrain the classifier to analyze my primary samples?

Thank you!

**Comment by ThomasWalter** [comment]
Hi. 

For the time being, the best is to omit the picking in the battery package. It should work on your data, but the data in the battery package is incomplete. We have to write this down somewhere. 

Thomas.
