### ISSUE TITLE
Error when opening CecogAnalyzer-1.6.1

### ISSUE THREAD

**Issue by DaniBodor** [CellCognition/cecog#229]
I am not able to start the CeCog Analyzer on Windows.
I had started it once before a couple of days ago and played around a bit, but since then whenever I try to run it (even after having uninstalled and reinstalled it several times in different locations) I get the following pop-up and the program fails to start:

![image](https://user-images.githubusercontent.com/14219087/141328390-40872e9b-4d70-4416-8463-d3b2a886a67c.png)

The CecogAnalyzer.exe.log states:

```
Traceback (most recent call last):
  File "CecogAnalyzer.py", line 42, in <module>
  File "PyQt5\QtGui.pyo", line 12, in <module>
  File "PyQt5\QtGui.pyo", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.

```

I don't know how to locate/open the corresponding files to try and figure out what's wrong...

**Comment by sommerc** [comment]
Hi @DaniBodor,

CellCognition project is orphaned since a while and the last binaries built are for Win7/8. Perhaps the version compiled from [Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/) works on Win10, but I have never tried.

Best,
Chris
